from src.classes._base import Class
from src.classes.artificer import Artificer
from src.classes.barbarian import Barbarian
from src.classes.bard import Bard
from src.classes.cleric import Cleric
from src.classes.druid import Druid
from src.classes.fighter import Fighter
from src.classes.monk import Monk
from src.classes.paladin import Paladin
from src.classes.ranger import Ranger
from src.classes.rogue import Rogue
from src.classes.sorcerer import Sorcerer
from src.classes.warlock import Warlock
from src.classes.wizard import Wizard
